name: publish

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    strategy:
      matrix:
        version: 
          - latest
          - 15
          - 14
          - 13
          - 12
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hbontempo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: POSTGRES_VERSION=${{ matrix.version }}
          platforms: linux/amd64
          push: true
          tags: hbontempo/posgres-hll:${{ matrix.version }}