name: publish_all

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  update-description:
    concurrency:
        group: update-description
        cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: hbontempo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: hbontempo/postgres-hll
          short-description: "Development PostgreSQL images with the HyperLogLog extension"

  version_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - 
        id: set-matrix
        run: |
          JSON=$(cat ./versions.json)
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  publish:
    timeout-minutes: 5
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: ${{fromJson(needs.version_matrix.outputs.matrix)}}       
    runs-on: ubuntu-latest
    steps:
      - 
        name: Invoke publish_image workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish_image
          inputs: '{ "postgres_version": "${{ matrix.postgres }}", "hll_version": "${{ matrix.hll }}" }'