name: publish

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    concurrency:
      group: release-${{ matrix.version }}
      cancel-in-progress: true
    timeout-minutes: 5
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        version: 
          - 'latest'
          - '15.1'
          - '15.0'
          - '15'
          - '14.6'
          - '14.5'
          - '14.4'
          - '14.3'
          - '14.2'
          - '14.1'
          - '14.0'
          - '14'
          - '13.9'
          - '13.8'
          - '13.7'
          - '13.6'
          - '13.5'
          - '13.4'
          - '13.3'
          - '13.2'
          - '13.1'
          - '13.0'
          - '13'
          - '12.13'
          - '12.12'
          - '12.11'
          - '12.10'
          - '12.9'
          - '12.8'
          - '12.7'
          - '12.6'
          - '12.5'
          - '12.4'
          - '12.3'
          - '12.2'
          - '12.1'
          - '12.0'
          - '12'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hbontempo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: POSTGRES_VERSION=${{ matrix.version }}
          platforms: linux/amd64
          push: true
          tags: hbontempo/posgres-hll:${{ matrix.version }}
          cache-from: type=registry,ref=hbontempo/posgres-hll:${{ matrix.version }}
          cache-to: type=inline