name: publish_all

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:

  get_configuration:
    uses: ./.github/workflows/configuration.yml

  update-description:
    needs: get_configuration
    concurrency:
        group: update-description
        cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: hbontempo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ needs.get_configuration.outputs.image_name }}
          short-description: "Development PostgreSQL images with the HyperLogLog extension"

  publish:
    needs: get_configuration
    timeout-minutes: 5
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: 
        config: ${{ fromJson(needs.get_configuration.outputs.matrix) }}     
    runs-on: ubuntu-latest
    steps:
      - 
        name: Invoke publish_image workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish_image
          inputs: '{ "postgres": "${{ matrix.config.postgres }}", "hll": "${{ matrix.config.hll }}", "main_tag": "${{ matrix.config.main_tag }}", "tags": "${{ matrix.config.tags }}" }'