name: publish_all

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  publish:
    strategy:
      fail-fast: false
      matrix: 
        config_file: 
          - debian.json
          - debian-bullseye.json
          - alpine.json
          - alpine316.json
          - alpine317.json
    uses: ./.github/workflows/publish.yml
    with:
      config_file: ${{ matrix.config_file }}
    secrets: inherit
