name: publish_image

on:
  workflow_dispatch:
    inputs: 
      postgres:
        description: 'PostgreSQL version'
        required: true
        default: 'latest'
        type: text
      hll:
        description: 'HLL plugin version'
        required: true
        default: '2.17'
        type: text
      main_tag:
        description: 'Maint tag that shouldbe used'
        required: true
        default: 'hbontempo/postgres-hll:latest-v2.17'
        type: text
      tags:
        description: 'All tags that should be used'
        required: true
        default: 'hbontempo/postgres-hll:latest-v2.17,hbontempo/postgres-hll:latest'
        type: text
      

jobs:
  publish:
    concurrency:
      group: publish-${{ inputs.main_tag }}
      cancel-in-progress: true
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hbontempo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            POSTGRES_VERSION=${{ inputs.postgres }}
            HLL_VERSION=${{ inputs.hll }}
          platforms: linux/amd64
          push: true
          tags: ${{ inputs.tags }}
          cache-from: type=registry,ref=${{ inputs.main_tag }}
          cache-to: type=inline