name: publish

on:
  # push:
  #   branches:
  #     - main
  workflow_call:
    inputs:
      config_file:
        description: 'Configuration file'
        default: debian.json
        required: true
        type: string
    secrets:
      DOCKER_HUB_ACCESS_TOKEN:
        required: true


jobs:

  get_configuration:
    uses: ./.github/workflows/configuration.yml
    with:
      config_file: ${{ inputs.config_file }}

  update-description:
    needs: get_configuration
    concurrency:
        group: update-description
        cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: hbontempo
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ needs.get_configuration.outputs.image_name }}
          short-description: "Development PostgreSQL images with the HyperLogLog extension"

  publish:
    needs: get_configuration
    timeout-minutes: 5
    concurrency:
      group: ${{ matrix.config.main_tag }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix: 
        config: ${{ fromJson(needs.get_configuration.outputs.matrix) }}     
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build and push
        id: build_push
        uses: ./.github/actions/publish_image
        with:
          dockerhub_username: hbontempo
          dockerhub_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          postgres: ${{ matrix.config.postgres }}
          hll: ${{ matrix.config.hll }}
          dockerfile: ${{ matrix.config.dockerfile }}
          main_tag: ${{ matrix.config.main_tag }}
          tags: ${{ matrix.config.tags }}
     