name: update_all

on:
  schedule:
    - cron: '0 10 * * *' # Daily at 10AM
  workflow_dispatch:


jobs:

  get_configuration:
    uses: ./.github/workflows/configuration.yml
      
  update:
    needs: get_configuration
    concurrency:
      group: update-${{ matrix.config.main_tag }}
      cancel-in-progress: true
    timeout-minutes: 5
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: 
        config: ${{ fromJson(needs.get_configuration.outputs.matrix) }}
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Docker Image Update Checker
        id: base_update_check
        uses: lucacome/docker-image-update-checker@v1.1.1
        with:
          base-image: library/postgres:${{ matrix.config.postgres }}
          image: ${{ matrix.config.main_tag }}
      - 
        name: Invoke publish_image workflow
        if: steps.base_update_check.outputs.needs-updating == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish_image
          inputs: '{ "postgres": "${{ matrix.config.postgres }}", "hll": "${{ matrix.config.hll }}", "main_tag": "${{ matrix.config.main_tag }}", "tags": "${{ matrix.config.tags }}" }'