name: update_all

on:
  push:
  schedule:
    - cron: '0 10 * * *' # Daily at 10AM
  workflow_dispatch:

jobs:

  publish:
    strategy:
      fail-fast: false
      matrix: 
        config_file: 
          - debian.json
          - debian-bullseye.json
          - alpine.json
          - alpine316.json
          # - alpine317.json
    uses: ./.github/workflows/update.yml
    with:
      image_name: hbontempo/postgres-hll
      config_file: ${{ matrix.config_file }}
    secrets: inherit
