name: update_all

on:
  schedule:
    - cron: '0 10 * * *' # Daily at 10AM
  workflow_dispatch:


jobs:

  version_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: set-matrix
        run: |
          JSON=$(cat ./versions.json)
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  update:
    concurrency:
      group: update-${{ matrix.postgres }}-v${{ matrix.hll }}
      cancel-in-progress: true
    timeout-minutes: 5
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: ${{fromJson(needs.version_matrix.outputs.matrix)}}
      
       
    runs-on: ubuntu-latest
    steps:
      - name: Docker Image Update Checker
        id: base_update_check
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: library/postgres:${{ matrix.postgres }}
          image: hbontempo/postgres-hll:${{ matrix.postgres }}-v${{ matrix.hll }}

      - 
        name: Invoke publish_image workflow
        if: steps.base_update_check.outputs.needs-updating == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish_image
          inputs: '{ "postgres_version": "${{ matrix.postgres }}", "hll_version": "${{ matrix.hll }}" }'
