name: versions_matrix

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      matrix:
        value: ${{ jobs.version_matrix.outputs.matrix }}

jobs:
  version_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.versions }}
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      - 
        id: set-matrix
        run: |
          echo "versions=$(jq -c '[.[] | {postgres: .postgres, hll: .hll, tags: ((["hbontempo/postgres-hll:" + .tags[]]) | join(","))}]' < ./versions.json)" >> $GITHUB_OUTPUT